name: Your New Jekyll Site
description: Developer, sysadmin, OSX user and crypto lover
permalink: /:title/
baseurl: /
url: https://lemarier.ca

author: 
  name: David Lemarier
  pgp: B79C03F69557EC55
  twitter:  DavidLemarier
  bio: I'm a web developer, network administrator, OSX user, crypto lover, off-road enthusiast and BBQ pitmaster.
  gravatar: 8a28146189fb92246a519124f61e60ce

exclude: [config.rb, nginx.conf, node_modules, package.json, README.md, supervisor.conf]

markdown: rdiscount
highlighter: rouge
gems:
  - jekyll-paginate
paginate: 20

rdiscount:
  extensions: [smart]

defaults:
    - 
      scope:
        path: "" # empty string for all files
        type: pages
      values:
        layout: default
    - 
      scope:
        path: "" # empty string for all files
        type: posts
      values:
        layout: post
    - 
      scope:
        path: ""
        type: drafts
      values:
        layout: post
